### ISSUE TITLE
Assertions need to account for type of Symbol

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-test-helpers#100]
tests/unit/helpers/sl/synchronous/contains-test.js

* "First non-optional argument must be an array, string or object"
* "Second non-optional argument must be an array, string or object"

**Comment by notmessenger** [comment]
https://github.com/emberjs/ember.js/issues/11673 is not going to be resolved at this time so calls to `Ember.typeOf()` that are compared to `'object'` must also contain logic similar to `&& 'symbol' != typeof`

**Comment by notmessenger** [comment]
Will need to use jshint ignore entries like in https://github.com/softlayer/sl-ember-components/blob/688911c66d7a678fab6ff935b332d76593b5b400/addon/components/sl-chart.js#L95

**Comment by erangeles** [comment]
@notmessenger taking this.

**Comment by erangeles** [comment]
apparently symbol testing must be put on hold. adding label backlog to this.

**Comment by notmessenger** [comment]
The `test-support/helpers/sl/synchronous/contains.js` file can be modified for now though so that the logic is correct.  You are correct that the test cannot be written yet though.

**Comment by erangeles** [comment]
@notmessenger I believe https://github.com/softlayer/sl-ember-test-helpers/commit/ac08ca802bf4046fb299ca3b7f52095c7fd810d8 addresses it, for accounting for symbol?

**Comment by notmessenger** [comment]
@erangeles Agreed.
