### ISSUE TITLE
Ember.typeOf( Symbol ) returns "function", which will cause problems in this code

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-test-helpers#102]
https://github.com/softlayer/sl-ember-test-helpers/blob/e0e301bb703557ae8bb76209900192dc51da4389/test-support/helpers/sl/utils/utils.js#L21

https://github.com/softlayer/sl-ember-test-helpers/blob/e0e301bb703557ae8bb76209900192dc51da4389/test-support/helpers/sl/synchronous/contains.js#L33

https://github.com/emberjs/ember.js/issues/11673 has been opened regarding this issue in Ember.js so depending on the timing of when the issue is worked on it might already be resolved or we will need to accommodate it via a workaround in our code via using `typeof`.  If we do the latter then we need to create an issue to remove our workaround once https://github.com/emberjs/ember.js/issues/11673 is resolved and released.

**Comment by stefanpenner** [comment]
im curious why this library doesn't just use `typeof` ?

**Comment by notmessenger** [comment]
@stefanpenner We have been able to replace Array.isArray() checks such as in https://github.com/softlayer/sl-ember-translate/commit/941cf0316f5b6bd5f4ce65d9cef9e75b4bcedbb9 when using Ember.typeOf(), as well as other standardization features Ember.typeOf() provides.  As such, we elected to enforce its usage across the board (https://github.com/softlayer/ember-style-guide#type-checking) for our projects for consistency.  And since any additional processing that might be incurred is only via the use of Ember.asserts() that get stripped out of production builds anyway we haven't encountered any issues.

If there is something missing in our approach or any recommendations you can make we're all ears!

**Comment by notmessenger** [comment]
https://github.com/emberjs/ember.js/issues/11673 is not going to be resolved at this time so calls to `Ember.typeOf()` that are compared to `'object'` must also contain logic similar to `&& 'symbol' != typeof`

**Comment by notmessenger** [comment]
Will need to use jshint ignore entries like in https://github.com/softlayer/sl-ember-components/blob/688911c66d7a678fab6ff935b332d76593b5b400/addon/components/sl-chart.js#L95
