### ISSUE TITLE
Refactor test(s) that check for parameter types to use assert.throws() call

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-test-helpers#111]
* Align with the pattern in https://github.com/softlayer/sl-ember-components/blob/develop/tests/unit/components/sl-chart-test.js#L99
* Do not include test for `Symbol`

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/issues/479 will modify the example to use

**Comment by erangeles** [comment]
@notmessenger taking this.
